name: simple_markdown
description: "A Flutter package for parsing and rendering markdown using low-level rendering APIs."
version: 0.2.0
homepage: https://github.com/tksuns12/simple_markdown

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
